sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- 2.7
before_install: gem install bundler -v 2.0.1
notifications:
  slack:
    rooms:
      secure: mcI1Fu2EB7zWv3iE83+fy7A7fe42YEr5zQYq36gvj1gPb0xVxPcDb/JarjO1ZQKrOGhNdtgGkPDUS+lC+jP6Sn/b6ONiqIAlSjaYEqi0WkqN9EuVxabIMFb4OXrw18xLU+YgBafd9TlLLB29HbWmbNNVOSAeVd78PvDjCrkAohzZmJ1Kr2E3dfJKB8B8khtXnFI35wjHS/7RXlssZE4EHpT+ZqPRmUN0gtSE0rT5T6uY2eiiHznsDzHVBqwrBzqD8nrOl8y9qFtqsqgSfpnsG4Vx6lNTrPszveQ2WRs7vCcRzpR1wkcwT82FxEvSuV2RAdv0s/eQE/qI/LD61F7Mnk/OEk7zQEQUBR2RktcF9nf36iYpLLLa06OPR3heZyMj39YibfhMwRXPJxVFEONbL0yjuof8PCIoNxwfOD0l1C+Rf57GdcdPzI8UTPhWehX6ESvIoMNK1l30MpWK6XSVgu0CWJfxdbqsj0z7fuE+Qf/6cYCbh3HG8dcIrdaL5ikFhAb7oStOTSpjffmIHEZVb2AM8PeqMtkPk4f8n/goZQ23X0KIazAXrtsvQ0buLLHAv6/4fGDVtH3dVYB7q4XCjiFjYdd8Rn96uk0imxl8Z1fwsg/eB3+o4b4AuEc31sC27p1bASE7SzPyDHT+pqCsvoJ11JhiYPvQMEbjpSIkExI=
